name: Latest Blog Posts
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@thetoriqul"
          max_post_count: 5
          template: "- <a href='$url'><img src='https://img.shields.io/badge/Medium-${title}-12100E?style=for-the-badge&logo=medium&logoColor=white'/></a>"
          comment_tag_name: "medium_posts"  # This must match exactly with the tags in README
          
      - name: Update DEV posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/thetoriqul"
          max_post_count: 5
          template: "- <a href='$url'><img src='https://img.shields.io/badge/DEV.to-${title}-0A0A0A?style=for-the-badge&logo=dev.to&logoColor=white'/></a>"
          comment_tag_name: "dev_posts"  # This must match exactly with the tags in README
