name: Latest Blog Posts
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@thetoriqul"
          max_post_count: 5
          template: "- <a href='$url'><img alt='Medium' src='https://img.shields.io/badge/Medium-${title// /_}-black?style=flat&logo=medium'/></a>"
          comment_tag_name: "medium_posts"
          transform: |
            {
              "title": {
                "replace": {
                  " ": "_",
                  ":": "",
                  "?": "",
                  "|": "",
                  "/": "_",
                  "\\": "_"
                }
              }
            }
          
      - name: Update DEV posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/thetoriqul"
          max_post_count: 5
          template: "- <a href='$url'><img alt='DEV' src='https://img.shields.io/badge/DEV-${title// /_}-black?style=flat&logo=dev.to'/></a>"
          comment_tag_name: "dev_posts"
          transform: |
            {
              "title": {
                "replace": {
                  " ": "_",
                  ":": "",
                  "?": "",
                  "|": "",
                  "/": "_",
                  "\\": "_"
                }
              }
            }
