name: Latest Blog Posts
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/thetoriqul, https://medium.com/feed/@thetoriqul"
          max_post_count: 5
          template: "[![](https://img.shields.io/badge/📝_$source-$title-2ea44f)](${url})"
          date_format: "mm/dd/yyyy"
          disable_sort: false
          tag_post_pre_newline: true