name: Latest Blog Posts Workflow
on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@thetoriqul"
          max_post_count: 5
          template: "• [$title]($url)"
          commit_message: "Updated README with latest Medium blog posts"
          commit_user_name: "blog-post-bot"
          commit_user_email: "toriqul.int@gmail.com"
          output_only_file_name: "README.md"
          retry_count: 3
          sort_by: published
          tag_post_pre_newline: true
